# pywb config file
# ========================================
#

collections:
    all: $all
    pywb:
        index_paths: cdx+http://tnaqa-pywb2.mirrorweb.com/published/cdx
        archive_paths: s3://mw-tna-webarchives/webarchives/
        acl_paths: true
        default_access: allow
# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true

